# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: stock data download Work Flow
on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 1 */3 *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download today's data from NSE
        run: |
          python live_data.py
      - name: Setup Github Config
        run: |
          git config --global user.name "HarideepSriperumbooduru"
          git config --global user.email "sriperumbooduri@msitprogram.net"
      - name: Commiting New Files
        run: |
          git pull origin master
          git add --all
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master
